.PHONY: clean All

All:
	@echo "----------Building project:[ singlyLinkedList - Debug ]----------"
	@cd "singlyLinkedList" && "$(MAKE)" -f  "singlyLinkedList.mk"
clean:
	@echo "----------Cleaning project:[ singlyLinkedList - Debug ]----------"
	@cd "singlyLinkedList" && "$(MAKE)" -f  "singlyLinkedList.mk" clean
