.PHONY: clean All

All:
	@echo "----------Building project:[ firstC - Debug ]----------"
	@cd "E:\tuvshinot\C\firstC" && "$(MAKE)" -f  "firstC.mk"
clean:
	@echo "----------Cleaning project:[ firstC - Debug ]----------"
	@cd "E:\tuvshinot\C\firstC" && "$(MAKE)" -f  "firstC.mk" clean
