.PHONY: clean All

All:
	@echo "----------Building project:[ WordPyramid - Debug ]----------"
	@cd "WordPyramid" && "$(MAKE)" -f  "WordPyramid.mk"
clean:
	@echo "----------Cleaning project:[ WordPyramid - Debug ]----------"
	@cd "WordPyramid" && "$(MAKE)" -f  "WordPyramid.mk" clean
