.PHONY: clean All

All:
	@echo "----------Building project:[ mini_swap_count - Debug ]----------"
	@cd "mini_swap_count" && "$(MAKE)" -f  "mini_swap_count.mk"
clean:
	@echo "----------Cleaning project:[ mini_swap_count - Debug ]----------"
	@cd "mini_swap_count" && "$(MAKE)" -f  "mini_swap_count.mk" clean
