.PHONY: clean All

All:
	@echo "----------Building project:[ ArraysAndPointers - Debug ]----------"
	@cd "AraysAndPointers" && "$(MAKE)" -f  "ArraysAndPointers.mk"
clean:
	@echo "----------Cleaning project:[ ArraysAndPointers - Debug ]----------"
	@cd "AraysAndPointers" && "$(MAKE)" -f  "ArraysAndPointers.mk" clean
